#ifndef GAME_SHARED_ANGELSCRIPT_SCRIPTAPI_ASCENTBITSET_H
#define GAME_SHARED_ANGELSCRIPT_SCRIPTAPI_ASCENTBITSET_H

class asIScriptEngine;

void RegisterScriptCEntBitSet( asIScriptEngine& engine );

#endif //GAME_SHARED_ANGELSCRIPT_SCRIPTAPI_ASCENTBITSET_H
