#ifndef GAME_SERVER_ANGELSCRIPT_SCRIPTAPI_SQL_ASHLSQL_H
#define GAME_SERVER_ANGELSCRIPT_SCRIPTAPI_SQL_ASHLSQL_H

class asIScriptEngine;

void RegisterScriptHLSQL( asIScriptEngine& engine );

#endif //GAME_SERVER_ANGELSCRIPT_SCRIPTAPI_SQL_ASHLSQL_H